name: todo_mon_c9
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  intl: ^0.20.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  flutter_slidable: ^3.1.0
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.4
  file_picker: ^8.0.6   # ✅ آخر إصدار متوافق مع Flutter 3.27+

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/splash.png
